In [1]:
#importing numpy library as np
import numpy as np

we are going to create a array in numpy and much more

In [8]:
a = np.array([5,2,6,2,7,5,6,8,2,9])
new_a=np.unique(a,return_counts = True)
print(type(new_a))
print(new_a)
print(new_a[0][new_a[1].argmax()])

<class 'tuple'>
(array([2, 5, 6, 7, 8, 9]), array([3, 2, 2, 1, 1, 1], dtype=int64))
2


In [3]:
#it create array in numpy
a=np.array([1,2,3,4,5,6])
print(a)
print(type(a)) 
print(a.shape) #it give the shape of array or dimention of array if it is 1-D it print (6,),if 2-D it print (6,4) 6 is no of
#rows and 4 is no of columns

[1 2 3 4 5 6]
<class 'numpy.ndarray'>
(6,)


In [4]:
#we can create any dimenion array and acces it by arrayname[index] 
b=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(b)
print(b.shape)
print(type(b))
# we can see that we have created a 3*3 array and we can acces by b[row index][column inde]

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
<class 'numpy.ndarray'>


In [5]:
#we can make array of only one,zeros e.t.c by writing
#below create a array on only ones of 3*3
c=np.ones((3,3))
print(c)
print(c.shape)
print(type(c))
b=np.zeros((4,4))   #it create array of zeros of 4*4
print(b)
print(type(b))
print(b.shape)
# we can also make array of constants

b=np.full((3,2),5)   #it create array of 3*2 of constant 5
print(b)
print(type(b))
print(b.shape)

#we can also create identity matrix as below  it create square identity matrix
d=np.eye(4)
print(d)
print(type(d))
print(d.shape)

# we can also create a random matrix as below
randommatrix=np.random.random((5,5))
print(randommatrix)
print(type(randommatrix))
print(randommatrix.shape)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
(3, 3)
<class 'numpy.ndarray'>
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
<class 'numpy.ndarray'>
(4, 4)
[[5 5]
 [5 5]
 [5 5]]
<class 'numpy.ndarray'>
(3, 2)
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
<class 'numpy.ndarray'>
(4, 4)
[[0.96041827 0.68119932 0.05945528 0.8314522  0.94678251]
 [0.65091276 0.03977958 0.69261985 0.04226643 0.35764469]
 [0.77004324 0.53368631 0.90622511 0.1481708  0.88860115]
 [0.31963478 0.7155895  0.96981207 0.53169768 0.56978991]
 [0.22739608 0.61572209 0.61756306 0.28972389 0.63723891]]
<class 'numpy.ndarray'>
(5, 5)


In [6]:
print(randommatrix[1,1])   #it will give element having index 1,1 means 1st row and 1st column
# to access we take matrix[rows index,column index]
#if we want to acces all rows of a given column
print(randommatrix[:,1])  # it will give all element of 1st coulmn
print(randommatrix[2,:]) #it will give all element of 2nd row
print(randommatrix[1:4,1:3])  #it will give element from 1st row to 4th row (excluding 4) and 1st column to 3rd coulmn(excluding 3)
# we can also update element of a matrix
randommatrix[1,1:]=1 #it update 1st row and column from 1st two end element   called as slicing
print(randommatrix)

0.039779578022233975
[0.68119932 0.03977958 0.53368631 0.7155895  0.61572209]
[0.77004324 0.53368631 0.90622511 0.1481708  0.88860115]
[[0.03977958 0.69261985]
 [0.53368631 0.90622511]
 [0.7155895  0.96981207]]
[[0.96041827 0.68119932 0.05945528 0.8314522  0.94678251]
 [0.65091276 1.         1.         1.         1.        ]
 [0.77004324 0.53368631 0.90622511 0.1481708  0.88860115]
 [0.31963478 0.7155895  0.96981207 0.53169768 0.56978991]
 [0.22739608 0.61572209 0.61756306 0.28972389 0.63723891]]


In [7]:
#we can also set some rows and column with any values i.e
d=np.zeros((3,3) ,dtype=np.int64)
#to set 1 row with 9 and 3 column with 7
d[1,:]=9
print(d)
d[:,-1]=7
print(d)

[[0 0 0]
 [9 9 9]
 [0 0 0]]
[[0 0 7]
 [9 9 7]
 [0 0 7]]


In [8]:
# data type of element of array is given as we can convert data type of element of any array by dtype=np.int/float/e.tc32/64 etc
print(a.dtype)
print(b.dtype)
print(c.dtype)
print(d.dtype)

int32
int32
float64
int64


In [9]:
#we can add /subtract two array/matrix
x=np.array([[1,2,3],[1,2,3],[1,2,3]])
y=np.array([[4,5,6],[4,5,6],[4,5,6]])
print(x+y)
print(x-y)
print(np.add(x,y))
print(np.subtract(x,y))

[[5 7 9]
 [5 7 9]
 [5 7 9]]
[[-3 -3 -3]
 [-3 -3 -3]
 [-3 -3 -3]]
[[5 7 9]
 [5 7 9]
 [5 7 9]]
[[-3 -3 -3]
 [-3 -3 -3]
 [-3 -3 -3]]


In [10]:
#we can multiply/divide element wise divison is normal not floor and we can also take squreroot of element wise
print(x*y)
print(np.multiply(x,y))
print(x/y)
print(np.divide(x,y))
print(np.sqrt(x))
print(np.sqrt(y))

[[ 4 10 18]
 [ 4 10 18]
 [ 4 10 18]]
[[ 4 10 18]
 [ 4 10 18]
 [ 4 10 18]]
[[0.25 0.4  0.5 ]
 [0.25 0.4  0.5 ]
 [0.25 0.4  0.5 ]]
[[0.25 0.4  0.5 ]
 [0.25 0.4  0.5 ]
 [0.25 0.4  0.5 ]]
[[1.         1.41421356 1.73205081]
 [1.         1.41421356 1.73205081]
 [1.         1.41421356 1.73205081]]
[[2.         2.23606798 2.44948974]
 [2.         2.23606798 2.44948974]
 [2.         2.23606798 2.44948974]]


In [11]:
#matrix multiplication we can do 
print(x)
print(y)
print(x.dot(y))
print(np.dot(x,y))

[[1 2 3]
 [1 2 3]
 [1 2 3]]
[[4 5 6]
 [4 5 6]
 [4 5 6]]
[[24 30 36]
 [24 30 36]
 [24 30 36]]
[[24 30 36]
 [24 30 36]
 [24 30 36]]


In [12]:
#we can also take dot product of two vector or multiplication of two vector
#vector is a linear array vector multiplication is a scaler
w=np.array([1,2,3,4])
z=np.array([1,2,3,4])
print(w.dot(z))
print(x)
print(np.sum(x))  #it give sum of all the element
print(np.sum(x,axis=0))   # it will sum along column
print(np.sum(x,axis=1))   #it will sum along row

30
[[1 2 3]
 [1 2 3]
 [1 2 3]]
18
[3 6 9]
[6 6 6]


In [13]:
print(w)
z=z*2
print(z)

[1 2 3 4]
[2 4 6 8]


In [14]:
#stacking means concatenation of array i.e
print(np.stack((w,z),axis=1))  #concatenating along  it made 1st array as 1st column and 2nd as 2nd column
print(np.stack((w,z),axis=0))    ##concatenating along  it made 1st array as 1st column and 2nd as 2nd column

[[1 2]
 [2 4]
 [3 6]
 [4 8]]
[[1 2 3 4]
 [2 4 6 8]]


In [15]:
# reshaping a numpy array i.e changing row and column as you wish
a=np.array([[1,2,3],[1,2,3],[1,2,3],[1,2,3]])
print(a)
print(a.reshape(6,2))   #it convert above array in 6 row and 2 column

[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]
[[1 2]
 [3 1]
 [2 3]
 [1 2]
 [3 1]
 [2 3]]


# NUMPY RANDOM MODULE 2ND LECTURE
- 1.rand :random values in a given shape
- 2.randn:return a sample (or samples) from the standard normal distribution
- 3.randint: return random integers from low(inclusive) to high (exclusive)
- 4.random :return random float in the half open interval [0,1.0)
- 5.choice: generate a random sample from given 1d array
- 6.shuffle: shuffle the content of sequence

In [25]:
#random is already in numpy
a=np.arange(10)+5
b=np.arange(10)
print(b)
print(a)

[0 1 2 3 4 5 6 7 8 9]
[ 5  6  7  8  9 10 11 12 13 14]


In [26]:
#now random shuffle  it suffle the sequence of array using shuffle
#we use seed to fix random no every time as generated 1st time it generate all time same random no
np.random.seed(1)
np.random.shuffle(a)
print(a)

[ 7 14 11  9  5  8  6 12 13 10]


In [27]:
#we can generate array of random no  using rand
a=np.random.rand(2,3)
print(a)

[[0.38791074 0.66974604 0.93553907]
 [0.84631092 0.31327352 0.52454816]]


In [28]:
a=np.random.randn(2,3)  # it return array from standard normal distribution we will see later standard normal distribution
print(a)

[[-1.50780766 -0.31529207  0.85817886]
 [ 0.07134299 -2.29230928 -1.41555249]]


In [29]:
a=np.random.randint(5,10,2)  #it will 2 integer from 5 to 10  by randint 
print(a)

[5 6]


In [30]:
#we can randomly pick element from a list of element by choice 
element=np.random.choice([1,2,3,4,5,7,5,6,6])
print(element)

6


some more numpy function
- min ,max
- mean
- median
- average
- variance
- standard deviation

In [32]:
a=np.array([[1,2,3,4],[7,6,2,0]])
print(np.min(a))     #it give minimum elementin a array
# in multidimentional array we can find min and max in a given direction if axis=0 min along each column and if axis=1 min along 
#each row
print(np.min(a,axis=0))
print(np.min(a,axis=1))

0
[1 2 2 0]
[1 0]


In [35]:
# mean/average  all the elements
print(np.mean(a))
print(np.mean(a,axis=0))
print(np.mean(a,axis=1))

3.125
[4.  4.  2.5 2. ]
[2.5  3.75]


In [45]:
#median it give median of data after accending it in increasing order
a=np.array([5,2,1,2,3,6])
print(np.median(a))

2.5


In [36]:
#average and mean are different thing. average is weighted   i.e
a=np.array([1,2,3,4,5])
w=np.array([1,2,3,4,5])
print(np.mean(a))
print(np.average(a,weights=w))  #weighted average is ((w[i]*a[i]+w[i+1]*w[i+1]+w[i+2]*a[i+2]+.......+w[n]*a[n])/(w1+w2+w3+w4+....+wn))

3.0
3.6666666666666665


In [39]:
#standard deviation 
a=np.array([1,5,4,2,0])
u=np.mean(a)
print(u)
sd=np.sqrt(np.mean(abs(a-u)**2))
print(sd)
#inbuilt function of standard deviation
deviation=np.std(a)
print(deviation)
# variance
print(sd**2)
print(np.var(a))

2.4
1.854723699099141
1.854723699099141
3.440000000000001
3.4400000000000004


# transpose  of a matrix

In [61]:
#to get transpose of a matrix
a=np.array([[1,3,5],[2,4,6]])
print(a)
print(a.T)

[[1 3 5]
 [2 4 6]]
[[1 2]
 [3 4]
 [5 6]]


# linear algebra
- scalar: it is a single number denoted as x
- vector: it is an array of scalars denoted by x
- a vector has n scalars :x1,x2,x3,.. xn
- x=[x1,
     x2,
     x3,
     ...
     xn]

In [49]:
# we can represent vector in both given form as requirement
x1=np.array([1,2,3,4])
x2=np.array([[1],[2],[3],[4]])
print(x1)
print(x2)
print(x1.shape)
print(x2.shape)
print(x1[0])   # it give 1st element
print(x2[0]) #it give 1st row
print(x2[0][0])
x2=x2.reshape((-1,2))   # it reshapes the vector in 2 dimension
print(x2)

[1 2 3 4]
[[1]
 [2]
 [3]
 [4]]
(4,)
(4, 1)
1
[1]
1
[[1 2]
 [3 4]]


# matrix and tensors
- MATRIX :it i s a 2d array of scalars ,denoted by X
- if no of rows =no of columns it is a square matrix
- Tensor: it is an array with more than 2 axes 
- tensor is a generalized of an array with more than 2 axes

In [55]:
# here x is a matrix
x=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(x)
print(x.shape)
# accesing element which is in 1st row and 1st column
print(x[1][1])
x[1:, : ]=17   # slicing
print(x)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
(4, 3)
5
[[ 1  2  3]
 [17 17 17]
 [17 17 17]
 [17 17 17]]


In [60]:
# here T is a tensor
t=np.array([[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]])
print(t.shape)  # it has 3 row ,3 column ,3 depth
print(t)

(3, 3, 3)
[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]


# matrix multiplictaion


In [63]:
a1=np.array([[1,2,3],[4,5,6],[7,8,9]])
a2=np.array([[10,20,30],[40,50,60],[70,80,90]])
print(a1)
print(a2)
print(np.dot(a1,a2))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 20 30]
 [40 50 60]
 [70 80 90]]
[[ 300  360  420]
 [ 660  810  960]
 [1020 1260 1500]]


# element wise multiplication

In [65]:
print(a1*a2)  #it multiply element wise

[[ 10  40  90]
 [160 250 360]
 [490 640 810]]


# NORM OF VECTOR

In [80]:
x=np.array([1,2,3,4,-20])
lp2=np.linalg.norm(x)
print(lp2)
lp1=np.linalg.norm(x,ord=1)
print(lp1)
lpinf=np.linalg.norm(x,ord=np.inf)
print(lpinf)
x1=np.array([[2,-2,1],[-1,2,-1],[2,-4,1]])
lpinf1=np.linalg.norm(x1,ord=np.inf)
print(lpinf1)
lp11=np.linalg.norm(x1,ord=1)
print(lp11)

20.73644135332772
30.0
20.0
7.0
8.0


# BROADCASTING
- you can add a scalar to vector ,and numpy will add it to each element in the vector
- x+a=xi+a
- similarly you can add a vector to matrix and numpy will add it the vector to each column of matrix


In [74]:
l=np.array([1,2,3,4,5])
l+=1
print(l)
l=l**2
print(l)
l+=1
print(np.sqrt(l))

[2 3 4 5 6]
[ 4  9 16 25 36]
[2.23606798 3.16227766 4.12310563 5.09901951 6.08276253]


In [77]:
l=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(l)
l+=1
print(l)
l=l**2
print(l)
l+=1
print(np.sqrt(l))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 2  3  4  5  6]
 [ 7  8  9 10 11]]
[[  4   9  16  25  36]
 [ 49  64  81 100 121]]
[[ 2.23606798  3.16227766  4.12310563  5.09901951  6.08276253]
 [ 7.07106781  8.06225775  9.05538514 10.04987562 11.04536102]]
